name: Generate RSS Feed

on:
  schedule:
    - cron: "10 1 * * *"  # JST 10:10
    - cron: "10 5 * * *"  # JST 14:10
    - cron: "10 8 * * *"  # JST 17:10
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y jq

      - name: Fetch previous RSS file
        run: |
          if [ -f rss.xml ]; then
            cp rss.xml previous_rss.xml
          else
            touch previous_rss.xml
          fi

      - name: Fetch JSON and Convert to RSS
        run: |
          curl -s -o news.json https://www.jst.go.jp/moonshot/js/newsitem_js.json

          TODAY=$(date -u +"%Y/%m/%d")
          FOURTEEN_DAYS_AGO=$(date -u -d "14 days ago" +"%Y/%m/%d")

          echo '<?xml version="1.0" encoding="UTF-8"?>' > new_rss.xml
          echo '<rss version="2.0"><channel>' >> new_rss.xml
          echo '<title>Moonshot News</title>' >> new_rss.xml
          echo '<link>https://www.jst.go.jp/moonshot</link>' >> new_rss.xml
          echo '<description>ムーンショット型研究開発制度の新着ニュース</description>' >> new_rss.xml

          jq -r --arg base_url "https://www.jst.go.jp" --arg start_date "$FOURTEEN_DAYS_AGO" --arg end_date "$TODAY" '
            map(select(.news_date >= $start_date and .news_date <= $end_date)) |
            .[] |
            "<item>
              <title>\(.top_and_news_title | @html)</title>
              <link>" + 
                (if .news_url | startswith("http") then .news_url else ($base_url + (.news_url | sub("^/"; ""))) end) +
              "</link>
              <guid isPermaLink=\"true\">" + 
                (if .news_url | startswith("http") then .news_url else ($base_url + (.news_url | sub("^/"; ""))) end) +
              "</guid>
              <pubDate>" + (.news_date + " 12:00:00 +0000") + "</pubDate>
            </item>"
          ' news.json >> new_rss.xml

          echo '</channel></rss>' >> new_rss.xml

      - name: Merge new items with previous RSS
        run: |
          if cmp -s new_rss.xml previous_rss.xml; then
            echo "No changes in RSS feed. Skipping commit."
            exit 0
          else
            mv new_rss.xml rss.xml
          fi

      - name: Commit and Push RSS
        run: |
          if git diff --quiet rss.xml; then
            echo "No changes in rss.xml. Skipping commit."
            exit 0
          fi
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add rss.xml
          git commit -m "Updated RSS feed"
          git push
